"""create_phase2_domain_schema

Revision ID: 71ffd0d7fccb
Revises: 
Create Date: 2026-09-19 11:34:55.620500+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ffd0d7fccb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.Enum('PDF', 'JPG', 'JPEG', 'PNG', name='document_type_enum'), nullable=False),
    sa.Column('document_role', sa.Enum('QUESTION_PAPER', 'ANSWER_KEY', 'UNKNOWN', name='document_role_enum'), server_default='UNKNOWN', nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'PARTIAL', 'FAILED', name='document_status_enum'), server_default='UPLOADED', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('file_size > 0', name='chk_document_file_size_positive'),
    sa.CheckConstraint('page_count IS NULL OR page_count >= 0', name='chk_document_page_count_non_negative'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    op.create_index('ix_documents_owner_status', 'documents', ['owner_id', 'status'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('answer_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('format_description', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)', name='chk_answer_key_confidence_range'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_keys_document_id'), 'answer_keys', ['document_id'], unique=False)
    op.create_index(op.f('ix_answer_keys_source_document_id'), 'answer_keys', ['source_document_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('ocr_used', sa.Boolean(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('rotation', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ocr_confidence IS NULL OR (ocr_confidence >= 0.0 AND ocr_confidence <= 1.0)', name='chk_ocr_confidence_range'),
    sa.CheckConstraint('page_number > 0', name='chk_page_number_positive'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_document_page_number')
    )
    op.create_index('ix_document_pages_doc_page', 'document_pages', ['document_id', 'page_number'], unique=False)
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='processing_job_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('attempt', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt >= 0', name='chk_processing_job_attempt_non_negative'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_document_id'), 'processing_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_processing_jobs_task_id'), 'processing_jobs', ['task_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.String(length=50), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('MCQ', 'TRUE_FALSE', 'SHORT_ANSWER', 'LONG_ANSWER', 'NUMERICAL', 'UNKNOWN', name='question_type_enum'), server_default='UNKNOWN', nullable=False),
    sa.Column('status', sa.Enum('EXTRACTED', 'PARTIAL', 'REVIEW_REQUIRED', name='question_status_enum'), server_default='EXTRACTED', nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answer_confidence', sa.Float(), nullable=True),
    sa.Column('answer_source', sa.Enum('EXTRACTED', 'ANSWER_KEY', 'AI_INFERRED', 'UNKNOWN', name='answer_source_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('answer_confidence IS NULL OR (answer_confidence >= 0.0 AND answer_confidence <= 1.0)', name='chk_question_answer_confidence_range'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)', name='chk_question_confidence_range'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_doc_qnum', 'questions', ['document_id', 'question_number'], unique=False)
    op.create_index(op.f('ix_questions_document_id'), 'questions', ['document_id'], unique=False)
    op.create_index(op.f('ix_questions_question_type'), 'questions', ['question_type'], unique=False)
    op.create_index(op.f('ix_questions_status'), 'questions', ['status'], unique=False)
    op.create_table('related_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('related_document_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('ANSWER_KEY', 'QUESTION_PAPER', 'SUPPLEMENT', 'OTHER', name='related_document_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('document_id != related_document_id', name='chk_related_document_no_self_ref'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'related_document_id', 'relationship_type', name='uq_related_document_pair_type')
    )
    op.create_index(op.f('ix_related_documents_document_id'), 'related_documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_related_documents_related_document_id'), 'related_documents', ['related_document_id'], unique=False)
    op.create_table('answer_mappings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('answer_key_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('question_reference', sa.String(length=100), nullable=True),
    sa.Column('answer_value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)', name='chk_answer_mapping_confidence_range'),
    sa.CheckConstraint('source_page IS NULL OR source_page > 0', name='chk_answer_mapping_source_page_positive'),
    sa.ForeignKeyConstraint(['answer_key_id'], ['answer_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_mappings_answer_key_id'), 'answer_mappings', ['answer_key_id'], unique=False)
    op.create_index(op.f('ix_answer_mappings_question_id'), 'answer_mappings', ['question_id'], unique=False)
    op.create_table('question_options',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position > 0', name='chk_question_option_position_positive'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'label', name='uq_question_option_label'),
    sa.UniqueConstraint('question_id', 'position', name='uq_question_option_position')
    )
    op.create_index(op.f('ix_question_options_question_id'), 'question_options', ['question_id'], unique=False)
    op.create_table('question_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('document_page_id', sa.UUID(), nullable=False),
    sa.Column('page_sequence', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('page_sequence > 0', name='chk_question_source_page_sequence_positive'),
    sa.ForeignKeyConstraint(['document_page_id'], ['document_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'document_page_id', name='uq_question_source_page')
    )
    op.create_index(op.f('ix_question_sources_document_page_id'), 'question_sources', ['document_page_id'], unique=False)
    op.create_index(op.f('ix_question_sources_question_id'), 'question_sources', ['question_id'], unique=False)
    op.create_table('review_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('page_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='review_severity_enum'), server_default='MEDIUM', nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'IGNORED', name='review_status_enum'), server_default='OPEN', nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)', name='chk_review_item_confidence_range'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_items_document_id'), 'review_items', ['document_id'], unique=False)
    op.create_index(op.f('ix_review_items_page_id'), 'review_items', ['page_id'], unique=False)
    op.create_index(op.f('ix_review_items_question_id'), 'review_items', ['question_id'], unique=False)
    op.create_index(op.f('ix_review_items_severity'), 'review_items', ['severity'], unique=False)
    op.create_index(op.f('ix_review_items_status'), 'review_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_items_status'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_severity'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_question_id'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_page_id'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_document_id'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_question_sources_question_id'), table_name='question_sources')
    op.drop_index(op.f('ix_question_sources_document_page_id'), table_name='question_sources')
    op.drop_table('question_sources')
    op.drop_index(op.f('ix_question_options_question_id'), table_name='question_options')
    op.drop_table('question_options')
    op.drop_index(op.f('ix_answer_mappings_question_id'), table_name='answer_mappings')
    op.drop_index(op.f('ix_answer_mappings_answer_key_id'), table_name='answer_mappings')
    op.drop_table('answer_mappings')
    op.drop_index(op.f('ix_related_documents_related_document_id'), table_name='related_documents')
    op.drop_index(op.f('ix_related_documents_document_id'), table_name='related_documents')
    op.drop_table('related_documents')
    op.drop_index(op.f('ix_questions_status'), table_name='questions')
    op.drop_index(op.f('ix_questions_question_type'), table_name='questions')
    op.drop_index(op.f('ix_questions_document_id'), table_name='questions')
    op.drop_index('ix_questions_doc_qnum', table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_processing_jobs_task_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_document_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_index('ix_document_pages_doc_page', table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_answer_keys_source_document_id'), table_name='answer_keys')
    op.drop_index(op.f('ix_answer_keys_document_id'), table_name='answer_keys')
    op.drop_table('answer_keys')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index('ix_documents_owner_status', table_name='documents')
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')

    # Drop custom PostgreSQL enum types in reverse dependency order
    for enum_name in [
        'related_document_type_enum',
        'answer_source_enum',
        'review_status_enum',
        'review_severity_enum',
        'question_status_enum',
        'question_type_enum',
        'processing_job_status_enum',
        'document_status_enum',
        'document_role_enum',
        'document_type_enum',
    ]:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
